import type {
  SchedulerOverviewMetric,
  SchedulerSessionSummary,
  SchedulerTrace,
} from "./types";

export const schedulerOverviewMetrics: SchedulerOverviewMetric[] = [
  {
    key: "requests",
    value: "1,284",
    detail: "1h · OpenAI compatible",
    trend: 8.2,
    tone: "neutral",
  },
  {
    key: "sticky",
    value: "72.6%",
    detail: "932 / 1,284 requests",
    trend: 3.4,
    tone: "success",
  },
  {
    key: "switch",
    value: "4.8%",
    detail: "61 requests · 74 switches",
    trend: -1.1,
    tone: "warning",
  },
  {
    key: "stability",
    value: "91.2%",
    detail: "same account through session",
    trend: 2.7,
    tone: "success",
  },
  {
    key: "cache",
    value: "78.4%",
    detail: "follow-up cache token rate",
    trend: 5.6,
    tone: "success",
  },
];

export const schedulerTraces: SchedulerTrace[] = [
  {
    id: "trace-01",
    requestId: "req_01J8Y7Q4H3K2",
    createdAt: "2026-08-10T16:42:18+08:00",
    userId: 18,
    userEmail: "dev@northstar.ai",
    apiKeyName: "Codex Team",
    groupId: 5,
    groupName: "OpenAI 主池",
    model: "gpt-5.6",
    requestType: "stream",
    cyberBlocked: false,
    sessionFingerprint: "a81f92c4",
    sessionSource: "session_header",
    sessionTurn: 6,
    decisionLayer: "load_balance",
    summary: "sticky_escaped_consecutive_errors",
    stickyHit: true,
    accountPath: [
      { id: 12, name: "codex-oauth-12" },
      { id: 15, name: "codex-oauth-15" },
    ],
    retryCount: 1,
    switchCount: 1,
    cacheReadTokens: 28_400,
    cacheEligibleTokens: 34_120,
    firstTokenMs: 1_284,
    durationMs: 8_420,
    status: "switched",
    attempts: [
      { id: "a1", kind: "sticky_match", accountId: 12, accountName: "codex-oauth-12", offsetMs: 4 },
      { id: "a2", kind: "upstream_failure", accountId: 12, accountName: "codex-oauth-12", offsetMs: 682, upstreamStatus: 429, reason: "rate_limit" },
      { id: "a3", kind: "same_account_retry", accountId: 12, accountName: "codex-oauth-12", offsetMs: 1_194, retryCount: 1, retryLimit: 3 },
      { id: "a4", kind: "upstream_failure", accountId: 12, accountName: "codex-oauth-12", offsetMs: 1_901, upstreamStatus: 429, reason: "rate_limit" },
      { id: "a5", kind: "sticky_escape", accountId: 12, accountName: "codex-oauth-12", offsetMs: 1_904, reason: "consecutive_errors" },
      { id: "a6", kind: "account_switch", accountId: 15, accountName: "codex-oauth-15", offsetMs: 1_911 },
      { id: "a7", kind: "request_success", accountId: 15, accountName: "codex-oauth-15", offsetMs: 8_420 },
    ],
    candidates: [
      { accountId: 15, accountName: "codex-oauth-15", rank: 1, baseScore: 7.82, stickyBonus: 0, totalScore: 7.82, state: "selected" },
      { accountId: 12, accountName: "codex-oauth-12", rank: 2, baseScore: 7.54, stickyBonus: 0.75, totalScore: 8.29, state: "tried", reason: "consecutive_errors" },
      { accountId: 9, accountName: "codex-oauth-09", rank: 3, baseScore: 7.31, stickyBonus: 0, totalScore: 7.31, state: "eligible" },
      { accountId: 4, accountName: "codex-oauth-04", rank: 4, baseScore: 6.92, stickyBonus: 0, totalScore: 6.92, state: "excluded", reason: "concurrency_full" },
      { accountId: 17, accountName: "codex-oauth-17", rank: 5, baseScore: 6.48, stickyBonus: 0, totalScore: 6.48, state: "excluded", reason: "quota_auto_pause_5h" },
    ],
  },
  {
    id: "trace-02",
    requestId: "req_01J8Y7PZDB9M",
    createdAt: "2026-08-10T16:41:54+08:00",
    userId: 42,
    userEmail: "ops@daybreak.dev",
    apiKeyName: "OpenCode",
    groupId: 5,
    groupName: "OpenAI 主池",
    model: "gpt-5.6-sol",
    requestType: "ws_v2",
    cyberBlocked: false,
    sessionFingerprint: "73cc91ae",
    sessionSource: "prompt_cache_key",
    sessionTurn: 11,
    decisionLayer: "session_hash",
    summary: "weighted_sticky_kept",
    stickyHit: true,
    accountPath: [{ id: 9, name: "codex-oauth-09" }],
    retryCount: 0,
    switchCount: 0,
    cacheReadTokens: 51_920,
    cacheEligibleTokens: 58_400,
    firstTokenMs: 784,
    durationMs: 5_210,
    status: "success",
    attempts: [
      { id: "a1", kind: "sticky_match", accountId: 9, accountName: "codex-oauth-09", offsetMs: 3 },
      { id: "a2", kind: "candidate_selected", accountId: 9, accountName: "codex-oauth-09", offsetMs: 8 },
      { id: "a3", kind: "request_success", accountId: 9, accountName: "codex-oauth-09", offsetMs: 5_210 },
    ],
    candidates: [
      { accountId: 9, accountName: "codex-oauth-09", rank: 1, baseScore: 7.42, stickyBonus: 0.75, totalScore: 8.17, state: "selected" },
      { accountId: 15, accountName: "codex-oauth-15", rank: 2, baseScore: 7.76, stickyBonus: 0, totalScore: 7.76, state: "eligible" },
      { accountId: 12, accountName: "codex-oauth-12", rank: 3, baseScore: 7.21, stickyBonus: 0, totalScore: 7.21, state: "eligible" },
    ],
  },
  {
    id: "trace-03",
    requestId: "req_01J8Y7NN5B8C",
    createdAt: "2026-08-10T16:40:37+08:00",
    userId: 18,
    userEmail: "dev@northstar.ai",
    apiKeyName: "Codex Team",
    groupId: 5,
    groupName: "OpenAI 主池",
    model: "gpt-5.6",
    requestType: "sync",
    cyberBlocked: false,
    sessionFingerprint: "b104dd72",
    sessionSource: "previous_response_id",
    sessionTurn: 3,
    decisionLayer: "previous_response_id",
    summary: "previous_response_kept",
    stickyHit: true,
    accountPath: [{ id: 15, name: "codex-oauth-15" }],
    retryCount: 0,
    switchCount: 0,
    cacheReadTokens: 18_240,
    cacheEligibleTokens: 22_100,
    firstTokenMs: 642,
    durationMs: 4_880,
    status: "success",
    attempts: [
      { id: "a1", kind: "sticky_match", accountId: 15, accountName: "codex-oauth-15", offsetMs: 2 },
      { id: "a2", kind: "request_success", accountId: 15, accountName: "codex-oauth-15", offsetMs: 4_880 },
    ],
    candidates: [
      { accountId: 15, accountName: "codex-oauth-15", rank: 1, baseScore: 7.63, stickyBonus: 1.5, totalScore: 9.13, state: "selected" },
    ],
  },
  {
    id: "trace-04",
    requestId: "req_01J8Y7M8R6VV",
    createdAt: "2026-08-10T16:39:12+08:00",
    userId: 77,
    userEmail: "api@orbit.sh",
    apiKeyName: "Production",
    groupId: 8,
    groupName: "低成本池",
    model: "gpt-5.5",
    requestType: "stream",
    cyberBlocked: false,
    sessionFingerprint: "dd0a4791",
    sessionSource: "content_fallback",
    sessionTurn: 1,
    decisionLayer: "load_balance",
    summary: "load_balance_best_score",
    stickyHit: false,
    accountPath: [{ id: 21, name: "openai-key-21" }],
    retryCount: 0,
    switchCount: 0,
    cacheReadTokens: 0,
    cacheEligibleTokens: 8_420,
    firstTokenMs: 923,
    durationMs: 3_742,
    status: "success",
    attempts: [
      { id: "a1", kind: "candidate_selected", accountId: 21, accountName: "openai-key-21", offsetMs: 7 },
      { id: "a2", kind: "request_success", accountId: 21, accountName: "openai-key-21", offsetMs: 3_742 },
    ],
    candidates: [
      { accountId: 21, accountName: "openai-key-21", rank: 1, baseScore: 8.14, stickyBonus: 0, totalScore: 8.14, state: "selected" },
      { accountId: 23, accountName: "openai-key-23", rank: 2, baseScore: 7.89, stickyBonus: 0, totalScore: 7.89, state: "eligible" },
    ],
  },
  {
    id: "trace-05",
    requestId: "req_01J8Y7KPX2A4",
    createdAt: "2026-08-10T16:38:29+08:00",
    userId: 63,
    userEmail: "agent@pinecone.cn",
    apiKeyName: "Agents",
    groupId: 5,
    groupName: "OpenAI 主池",
    model: "gpt-5.6-terra",
    requestType: "sync",
    cyberBlocked: false,
    sessionFingerprint: "194ef8ba",
    sessionSource: "session_header",
    sessionTurn: 8,
    decisionLayer: "load_balance",
    summary: "sticky_escaped_concurrency",
    stickyHit: true,
    accountPath: [
      { id: 9, name: "codex-oauth-09" },
      { id: 12, name: "codex-oauth-12" },
    ],
    retryCount: 0,
    switchCount: 1,
    cacheReadTokens: 32_110,
    cacheEligibleTokens: 42_700,
    firstTokenMs: 1_106,
    durationMs: 6_934,
    status: "switched",
    attempts: [
      { id: "a1", kind: "sticky_match", accountId: 9, accountName: "codex-oauth-09", offsetMs: 3 },
      { id: "a2", kind: "sticky_escape", accountId: 9, accountName: "codex-oauth-09", offsetMs: 10, reason: "concurrency_full" },
      { id: "a3", kind: "account_switch", accountId: 12, accountName: "codex-oauth-12", offsetMs: 18 },
      { id: "a4", kind: "request_success", accountId: 12, accountName: "codex-oauth-12", offsetMs: 6_934 },
    ],
    candidates: [
      { accountId: 12, accountName: "codex-oauth-12", rank: 1, baseScore: 7.68, stickyBonus: 0, totalScore: 7.68, state: "selected" },
      { accountId: 9, accountName: "codex-oauth-09", rank: 2, baseScore: 7.58, stickyBonus: 0.75, totalScore: 8.33, state: "excluded", reason: "concurrency_full" },
      { accountId: 15, accountName: "codex-oauth-15", rank: 3, baseScore: 7.44, stickyBonus: 0, totalScore: 7.44, state: "eligible" },
    ],
  },
  {
    id: "trace-06",
    requestId: "req_01J8Y7JCM4E1",
    createdAt: "2026-08-10T16:37:03+08:00",
    userId: 91,
    userEmail: "lab@vector.run",
    apiKeyName: "Research",
    groupId: 5,
    groupName: "OpenAI 主池",
    model: "gpt-5.6",
    requestType: "stream",
    cyberBlocked: true,
    sessionFingerprint: null,
    sessionSource: "none",
    sessionTurn: null,
    decisionLayer: "load_balance",
    summary: "no_available_account",
    stickyHit: false,
    accountPath: [],
    retryCount: 0,
    switchCount: 0,
    cacheReadTokens: 0,
    cacheEligibleTokens: 0,
    firstTokenMs: null,
    durationMs: 214,
    status: "failed",
    attempts: [
      { id: "a1", kind: "sticky_escape", offsetMs: 202, reason: "no_available_account" },
    ],
    candidates: [
      { accountId: 9, accountName: "codex-oauth-09", rank: 1, baseScore: 0, stickyBonus: 0, totalScore: 0, state: "excluded", reason: "runtime_blocked" },
      { accountId: 12, accountName: "codex-oauth-12", rank: 2, baseScore: 0, stickyBonus: 0, totalScore: 0, state: "excluded", reason: "concurrency_full" },
      { accountId: 15, accountName: "codex-oauth-15", rank: 3, baseScore: 0, stickyBonus: 0, totalScore: 0, state: "excluded", reason: "quota_auto_pause_5h" },
    ],
  },
];

export const schedulerSessions: SchedulerSessionSummary[] = [
  {
    fingerprint: "73cc91ae",
    source: "prompt_cache_key",
    userId: 42,
    userEmail: "ops@daybreak.dev",
    apiKeyName: "OpenCode",
    groupName: "OpenAI 主池",
    model: "gpt-5.6-sol",
    turns: 11,
    accountIds: [9],
    accountNames: { 9: "codex-oauth-09" },
    switchCount: 0,
    stickyHitRate: 0.91,
    followUpCacheRate: 0.889,
    lastActiveAt: "2026-08-10T16:41:54+08:00",
    turnAccounts: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
  },
  {
    fingerprint: "a81f92c4",
    source: "session_header",
    userId: 18,
    userEmail: "dev@northstar.ai",
    apiKeyName: "Codex Team",
    groupName: "OpenAI 主池",
    model: "gpt-5.6",
    turns: 6,
    accountIds: [12, 15],
    accountNames: { 12: "codex-oauth-12", 15: "codex-oauth-15" },
    switchCount: 1,
    stickyHitRate: 0.83,
    followUpCacheRate: 0.832,
    lastActiveAt: "2026-08-10T16:42:18+08:00",
    turnAccounts: [12, 12, 12, 12, 12, 15],
  },
  {
    fingerprint: "194ef8ba",
    source: "session_header",
    userId: 63,
    userEmail: "agent@pinecone.cn",
    apiKeyName: "Agents",
    groupName: "OpenAI 主池",
    model: "gpt-5.6-terra",
    turns: 8,
    accountIds: [9, 12],
    accountNames: { 9: "codex-oauth-09", 12: "codex-oauth-12" },
    switchCount: 1,
    stickyHitRate: 0.75,
    followUpCacheRate: 0.752,
    lastActiveAt: "2026-08-10T16:38:29+08:00",
    turnAccounts: [9, 9, 9, 9, 9, 9, 9, 12],
  },
  {
    fingerprint: "b104dd72",
    source: "previous_response_id",
    userId: 18,
    userEmail: "dev@northstar.ai",
    apiKeyName: "Codex Team",
    groupName: "OpenAI 主池",
    model: "gpt-5.6",
    turns: 3,
    accountIds: [15],
    accountNames: { 15: "codex-oauth-15" },
    switchCount: 0,
    stickyHitRate: 1,
    followUpCacheRate: 0.825,
    lastActiveAt: "2026-08-10T16:40:37+08:00",
    turnAccounts: [15, 15, 15],
  },
];
